# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/itslivetools',
                'doc_host': 'https://e-marshall.github.io',
                'git_url': 'https://github.com/e-marshall/itslivetools',
                'lib_path': 'itslivetools'},
  'syms': { 'itslivetools.access': { 'itslivetools.access.find_granule_by_point': ( 'access.html#find_granule_by_point',
                                                                                    'itslivetools/access.py'),
                                     'itslivetools.access.find_granule_by_zone': ( 'access.html#find_granule_by_zone',
                                                                                   'itslivetools/access.py'),
                                     'itslivetools.access.get_bbox': ('access.html#get_bbox', 'itslivetools/access.py'),
                                     'itslivetools.access.read_in_s3': ('access.html#read_in_s3', 'itslivetools/access.py')}}}
