# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_mosaic_velocity.ipynb.

# %% auto 0
__all__ = ['read_in_itslive_vars', 'extract_glacier_velocity_ds', 'calc_median_velocity']

# %% ../nbs/02_mosaic_velocity.ipynb 3
import os
import json

import geopandas as gpd
import numpy as np
import xarray as xr
import pandas as pd
import rioxarray as rxr

import geoviews as gv
import hvplot.pandas
import hvplot.xarray
import matplotlib.pyplot as plt

# %% ../nbs/02_mosaic_velocity.ipynb 9
def read_in_itslive_vars(path, crs):

    '''takes path to directory where cropped data var objects stored (output of gdalwarp fn)
    '''

    #make list of all files in dir
    ls = os.listdir(path)

    xr_ls = []
    #for each file in dir, read in and rename var 
    for var in range(len(ls)):
        ds = xr.open_dataset(os.path.join(path, ls[var]), chunks='auto')
        ds = ds.rename({'Band1':ls[var].split('_mosaic')[0]})
        xr_ls.append(ds)
        
    ds_allvars = xr.merge(xr_ls)

    ds_allvars.rio.write_crs(crs, inplace=True)
    return ds_allvars

# %% ../nbs/02_mosaic_velocity.ipynb 15
def extract_glacier_velocity_ds(rgi_gpdf, itslive_ds, rgiid):

    rgi_single = rgi_gpdf.loc[rgi_gpdf['RGIId'] == rgiid]

    ds = itslive_ds.rio.clip(rgi_single.geometry, rgi_single.crs)

    return ds

# %% ../nbs/02_mosaic_velocity.ipynb 17
def calc_median_velocity(ds):
    med = ds.v.load().median()
    return med #m/y
